# Generated by Django 4.1.7 on 2023-03-31 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBakery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='publisher',
            new_name='propietario',
        ),
    ]
