# Generated by Django 4.1.7 on 2023-04-01 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBakery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad_producto',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HomeBakery.producto'),
        ),
        migrations.DeleteModel(
            name='ProductoPedido',
        ),
    ]
