# Generated by Django 4.1.7 on 2023-03-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBakery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
